// <auto-generated />
namespace CMS.DataAccsess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PageAddClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageAddClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201809070842023_PageAddClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
